# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie Radar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie Radar

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

  target 'Movie RadarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
